server {
    listen 80;
    server_name _;
    client_max_body_size 10m;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/app/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/app/public;
        fastcgi_param PATH_INFO "";
        fastcgi_pass backend:9000;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
